version: '3.6'
services:
    db:
        container_name: shodan_db
        image: mariadb
        environment:
            - MYSQL_DATABASE=<DB_NAME_HERE>
            - MYSQL_USER=<DB_USER_HERE>
            - MYSQL_PASSWORD=<DB_PASSWORD_HERE>
            - MYSQL_ROOT_PASSWORD=<DB_ROOT_PASSWORD_HERE>
        ports:
            - 3306:3306
        healthcheck:
            test: 'mysql -u root --password=<DB_ROOT_PASSWORD_HERE> -e "show database"'
            timeout: 12s
            retries: 10
        volumes:
            - ./mariadb:/var/lib/mysql
        networks:
            - shodan_gateway
    shodan_streamer:
        container_name: shodan_stream
        build: ./shodan
        depends_on:
            - db
        volumes:
            - ./shodan/bot:/shodan
        command: python /shodan/streamer.py
        networks:
            - shodan_gateway
networks:
    shodan_gateway: {}
