version: '3.6'
services:
    shodan_db:
        container_name: shodan_db
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB=<DB_NAME_HERE>
            - POSTGRES_USER=<DB_USER_HERE>
            - POSTGRES_PASSWORD=<DB_PASSWORD_HERE>
        healthcheck:
            test: "pg_isready -U <DB_USER_HERE>"
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./db-data:/var/lib/postgresql/data
        networks:
            - shodan_gateway

    shodan_streamer:
        container_name: shodan_streamer
        build: ./shodan
        depends_on:
            - shodan_db
        volumes:
            - ./shodan/bot:/shodan
        command: python /shodan/streamer.py
        networks:
            - shodan_gateway
        tty: true
        stdin_open: true

networks:
    shodan_gateway: {}
